name: Package Build
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "13 */6 * * *"
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker run -e RCLONE_CONFIG_URL=${{ secrets.RCLONE_CONFIG_URL }} -e RCLONE_COMMANDS_URL=${{ secrets.RCLONE_COMMANDS_URL }} registry.gitlab.com/viperadnan/rclone-sync
